-- public.users definition
-- Drop table
-- DROP TABLE public.users;
CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(250) NOT NULL,
	email varchar(250) NULL,
	phone varchar(250) NULL,
	username varchar NOT NULL,
	"password" varchar NOT NULL,
	confirmed bool NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- public.units definition
-- Drop table
-- DROP TABLE public.units;
CREATE TABLE public.units (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(250) NOT NULL,
	details varchar(250) NOT NULL,
	updated_at timestamp NULL,
	user_id int8 NULL,
	CONSTRAINT units_pkey PRIMARY KEY (id)
);

-- public.units foreign keys
ALTER TABLE public.units ADD CONSTRAINT units_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);