CREATE TABLE users (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(250) NOT NULL,
    email VARCHAR(250) NULL,
    phone VARCHAR(250) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE units (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(250) NOT NULL,
    details VARCHAR(250) NOT NULL,
    updated_at timestamp NULL,
    user_id int8 NULL,
    CONSTRAINT units_pkey PRIMARY KEY (id)
);

ALTER TABLE units ADD CONSTRAINT units_fkey FOREIGN KEY (user_id) REFERENCES users(id);